CREATE TABLE IF NOT EXISTS REDIRECTION(
    SOURCE_URL VARCHAR NOT NULL,
    ALIAS_NAME VARCHAR NOT NULL,
    IP_ADDRESS VARCHAR NOT NULL,
    CREATE_TIME TIMESTAMP,
    BROWSER VARCHAR,
    PLATFORM VARCHAR,
    PRIMARY KEY (SOURCE_URL, ALIAS_NAME, IP_ADDRESS)
);